SALARY = "salary"
FASHION = "fashion"
GROCERIES = "groceries"
GASTRONOMY = "gastronomy"
INSURANCE = "insurance"
MOBILITY = "mobility"
LEISURE = "leisure"
LIVING = "living"
DOCTOR = "doctor"
CLUBS = "clubs"
DONATIONS = "donations"
CATS = "cats"
TRAINING = "training"

UNDEFINED = "undefined"
